[font]
size = 11.0
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }

[window]
blur = true
opacity = 0.98
decorations = "buttonless"
